### ISSUE TITLE
Access artifacts across jobs?

### ISSUE THREAD

**Issue by drozzy** [Paperspace/gradient-cli#148]
Is it possible to access an artifact from one job inside another job?

**Comment by mkutsovsky** [comment]
You can use the sdk to get the artifacts of any job once it completes. Artifacts are only created and uploaded to a bucket after a job tearsdown.

 If you want to share them in between jobs that are both running then you need to either use the shared filesystem (/storage) or ssh into the job itself.

**Comment by drozzy** [comment]
What's the use case for them? I know floydhub allows them to be accessed from another job like a regular directory, which seems useful: https://docs.floydhub.com/guides/data/mounting_data/#mounting-the-output-of-another-job

Why would I ever use artifact dir instead of a storage dir?
Just find it confusing a bit.
