### ISSUE TITLE
Installation Suggestion: use pipx gradient

### ISSUE THREAD

**Issue by itsayellow** [Paperspace/gradient-cli#21]
You might want to suggest using pipx to install the gradient CLI:
https://github.com/pipxproject/pipx

The nice thing about pipx is that it:
* doesn't require putting gradient and required libraries in the system or user base python installations
* would put the gradient binary in the user's path no matter which virtual env the user is using
* makes its own virtual environment just for the gradient tool and handles all of that
* works mostly like pip, except with the above benefits.

**Comment by BartoszCki** [comment]
Hi again!

That's really interesting. Thanks for the tip. 
Unfortunately currently we still have to support python2.7, but maybe in the future.
