### ISSUE TITLE
Failed to create resource

### ISSUE THREAD

**Issue by andreaschandra** [Paperspace/gradient-cli#327]
running the command:
`gradient notebooks start --id [id] --machineType Free-CPU`

gives an output
`Failed to create resource: We are currently out of capacity for the selected VM type. Try again in a few minutes, or select a different instance.`

But, if I tried on Web UI. it works. I think it doesn't synchronize really well

**Comment by TheCrazyT** [comment]
Today I noticed the same.
Maybe it is intensional?

**Comment by lamroger** [comment]
We've tuned our capacity lookups but please let us know if you see it happening again. Thanks!
