### ISSUE TITLE
Experiment worker command base64-encoded

### ISSUE THREAD

**Issue by danipozo** [Paperspace/gradient-cli#332]
`gradient experiments details --id <id>` outputs a table with various data. The "Worker Command" row is presented encoded in base64. Steps to reproduce should just be running that command with some experiment id. Feel free to ask if you need any more detail from my particular experiment.

**Comment by lamroger** [comment]
Thanks for the bug report! We're introducing a new product called Workflows if you want to try it out which supports similar workloads to experiments.
