### ISSUE TITLE
Update older example or create new ML5js example PLEASE

### ISSUE THREAD

**Issue by quintendewilde** [Paperspace/gradient-cli#338]
It's fun to learn through tutorials but they should work. 

I'm following this tutorial. And it's outdated and should be updated because it's a very easy way of learning with light tools. 

https://blog.paperspace.com/creating-your-own-style-transfer-mirror/

I get this error, when trying to overcome all the outdated obstacles. 
But now I'm stuck without a proper log. 

gradient experiments create singlenode --container cvalenzuelab/styletransfer --machineType P5000 --command './run.sh' --projectId 'Style Transfer training'
Failed to create resource: Project not found for handle Style Transfer training
Project not found

Please help there are more people on the community page that want this to work. But got no reaction from Paperspace

Sorry for the begging :)

**Comment by lamroger** [comment]
Thanks I'll let our content team know!
