### ISSUE TITLE
dead link in documentation

### ISSUE THREAD

**Issue by OrysB** [Paperspace/gradient-cli#340]
Dear Gradient-CLI Team,
I'm not sure if this is the right place to report this, but I noticed a link in the documentation is not working.
On page:
https://docs.paperspace.com/gradient/projects/gradientci-v2

there is a link to the config documentation:
https://github.com/Paperspace/Docs/tree/dace77bbd70b824f1dfd4bf27fc24deef5218d16/experiments/gradient-config.yaml.md

Unfortunateley I get a 404 following it.
Greetings
Orys

**Comment by lamroger** [comment]
Thanks for the heads up! We've revamped our documentation - hope it helps!
