### ISSUE TITLE
Failing to start notebook

### ISSUE THREAD

**Issue by macsunmood** [Paperspace/gradient-cli#361]
I'm trying to start an instance of an existing notebook:
`gradient notebooks start --id [id] --machineType Free-P5000`

and get in return:
`Failed to create resource: Cluster null not found`

specifying any cluster ID doesn't change anything and the output remains the same.

A bug ?

**Comment by lamroger** [comment]
Thanks for the report! I was able to reproduce and will fix soon.

**Comment by lamroger** [comment]
We pushed a fix - but please reopen if you're still having issues. Thanks!
