### ISSUE TITLE
Update Readme.md

### ISSUE THREAD

**Issue by nziermann** [Paperspace/gradient-cli#46]
I found two outdated or currently not working commands while trying to execute my container:

1. The --project option was ignored but providing --projectId worked.
2. The example for the --command option had as error message: 
Error: Missing argument "SCRIPT...". Upon providing a script the originally provided command was ignored. Instead I had to use the --shell option to execute the correct call.

**Comment by BartoszCki** [comment]
Hi there!

Thanks for the tip! The fixed README, along with other minor fix, is already deployed as 0.2.3.

BTW: New docs for the Gradient CLI client should be published soon. The README will be rewritten from scratch as well.

**Comment by jaredscheib** [comment]
thanks @nziermann and @BartoszCki! and much appreciated on letting us know, @nziermann – if the updated README and fixes in 0.2.3 don't correct these, or if you run into other issues, we're all ears!

**Comment by nziermann** [comment]
Unfortunately I think that the commands in the README are still not quite correct. Apperently I was unclear in my issue description. In #49 you can see what I meant.

**Comment by jaredscheib** [comment]
right on. so just to confirm, does your merged PR address and take care of this issue then, @nziermann?

**Comment by nziermann** [comment]
Yeah it does. Thanks

**Comment by jaredscheib** [comment]
great. thank you
