### ISSUE TITLE
Support gradient_statsd from the CLI

### ISSUE THREAD

**Issue by croesuslab** [Paperspace/gradient-cli#52]
Hi,

Is it possible to specify the metric names when creating a job (like the Job Builder)? There doesn't appear to have a parameter for that in the gradient jobs create params list.

Thanks!

**Comment by mkutsovsky** [comment]
we are planning on adding that capability to the CLI soon for jobs & experiments, appreciate the note

**Comment by jaredscheib** [comment]
@croesuslab Thanks for writing in – what you're requesting is not currently possible, but as @mkutsovsky mentioned, we're planning on adding it soon. Thank you again!
