### ISSUE TITLE
When providing --ignoreFiles comma separated the code returns Attribute error.

### ISSUE THREAD

**Issue by EvDuijnhoven** [Paperspace/gradient-cli#96]
The command below with the --ignoreFiles field set
```
gradient experiments run single node \
--name test \
--projectid 12345 \
--container paperspace/tensorflow-python \
--machineType V100 \
--command 'python main.py' \
--ignoreFiles "file1,file2,file3,folder1,folder2,folder3"
```

Returns the following error
```
file_paths = self._retrieve_file_paths(workspace_path, ignore_files)
File "/lib/python3.7/site-packages/gradient/workspace.py", line 59, in _retrieve_file_paths
    exclude += ignored_files.split(',')
AttributeError: 'list' object has no attribute 'split'
```

**Comment by mkulaczkowski** [comment]
@EvDuijnhoven thank you for reporting this - may I ask what version of CLI you were using? you can check it by `gradient version`

**Comment by EvDuijnhoven** [comment]
Hey @mkulaczkowski,

The version I am using is 0.3.1. I think a simple fix would be removing the .split(',') from this line because it seems that the split already occurs earlier in the code. Didn't look into the details though.

**Comment by BartoszCki** [comment]
Hi there @EvDuijnhoven 
New patch version (0.3.2) has just been released fixing this issue.
